ClassLength:
  Max: 200

LineLength:
  Max: 120

MethodLength:
  Max: 40

AbcSize:
  Max: 50

CyclomaticComplexity:
  Max: 10

PerceivedComplexity:
  Max: 15

StringLiterals:
  EnforcedStyle: double_quotes

MultilineBlockChain:
  Enabled: false
