ClassLength:
  Max: 200

LineLength:
  Max: 120

MethodLength:
  Max: 40

AbcSize:
  Max: 50

CyclomaticComplexity:
  Max: 20

PerceivedComplexity:
  Max: 20

StringLiterals:
  EnforcedStyle: double_quotes

MultilineBlockChain:
  Enabled: false
